name: Deploy DynamoDB Statefile DB.
on:
  push:
    branches: [ main ]
jobs:
  statefile-db-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Terraform
      id: s3-statefile-database
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd terraform/
        terraform init
        terraform plan
        terraform apply -input=false -auto-approve
